db_name: servicebroker
db_port: "3306"
gcp_service_broker_enable_global_access_to_plans: true
gsb_brokerpak_config: '{}'
gsb_compatibility_enable_catalog_schemas: "false"
gsb_compatibility_enable_cf_sharing: "false"
gsb_compatibility_enable_eol_services: "false"
gsb_compatibility_enable_gcp_beta_services: "true"
gsb_compatibility_enable_gcp_deprecated_services: "false"
gsb_compatibility_enable_input_validation: "true"
gsb_compatibility_enable_preview_services: "true"
gsb_compatibility_enable_terraform_services: "false"
gsb_compatibility_enable_unmaintained_services: "false"
gsb_compatibility_three_to_four_legacy_plans: "false"
gsb_service_google_bigquery_bind_defaults: '{}'
gsb_service_google_bigquery_enabled: true
gsb_service_google_bigquery_provision_defaults: '{}'
gsb_service_google_bigquery_whitelist: bigquery.dataViewer,bigquery.dataEditor,bigquery.dataOwner,bigquery.user,bigquery.jobUser
gsb_service_google_bigtable_bind_defaults: '{}'
gsb_service_google_bigtable_enabled: true
gsb_service_google_bigtable_provision_defaults: '{}'
gsb_service_google_bigtable_whitelist: bigtable.user,bigtable.reader,bigtable.viewer
gsb_service_google_cloudsql_mysql_bind_defaults: '{}'
gsb_service_google_cloudsql_mysql_enabled: true
gsb_service_google_cloudsql_mysql_provision_defaults: '{}'
gsb_service_google_cloudsql_mysql_whitelist: cloudsql.editor,cloudsql.viewer,cloudsql.client
gsb_service_google_cloudsql_postgres_bind_defaults: '{}'
gsb_service_google_cloudsql_postgres_enabled: true
gsb_service_google_cloudsql_postgres_provision_defaults: '{}'
gsb_service_google_cloudsql_postgres_whitelist: cloudsql.editor,cloudsql.viewer,cloudsql.client
gsb_service_google_dataflow_enabled: true
gsb_service_google_datastore_enabled: true
gsb_service_google_dialogflow_enabled: true
gsb_service_google_firestore_enabled: true
gsb_service_google_ml_apis_bind_defaults: '{}'
gsb_service_google_ml_apis_enabled: true
gsb_service_google_ml_apis_provision_defaults: '{}'
gsb_service_google_ml_apis_whitelist: ml.developer,ml.viewer,ml.modelOwner,ml.modelUser,ml.jobOwner,ml.operationOwner
gsb_service_google_pubsub_bind_defaults: '{}'
gsb_service_google_pubsub_enabled: true
gsb_service_google_pubsub_provision_defaults: '{}'
gsb_service_google_pubsub_whitelist: pubsub.publisher,pubsub.subscriber,pubsub.viewer,pubsub.editor
gsb_service_google_spanner_bind_defaults: '{}'
gsb_service_google_spanner_enabled: true
gsb_service_google_spanner_provision_defaults: '{}'
gsb_service_google_spanner_whitelist: spanner.databaseAdmin,spanner.databaseReader,spanner.databaseUser,spanner.viewer
gsb_service_google_stackdriver_debugger_enabled: true
gsb_service_google_stackdriver_monitoring_enabled: true
gsb_service_google_stackdriver_profiler_enabled: true
gsb_service_google_stackdriver_trace_enabled: true
gsb_service_google_storage_bind_defaults: '{}'
gsb_service_google_storage_enabled: true
gsb_service_google_storage_provision_defaults: '{}'
gsb_service_google_storage_whitelist: storage.objectCreator,storage.objectViewer,storage.objectAdmin
