---
platform: linux
image_resource:
  type: docker-image
  source: {repository: jrjohnsongoog/omgci}
inputs:
- name: omg-src-in
- name: omg-src-ci
- name: omg-env
  path: omg-env-in
outputs:
- name: omg-env
  path: omg-env-out
run:
  path: omg-src-ci/ci/tasks/create-infrastructure.sh
