---
platform: linux
image_resource:
  type: docker-image
  source: {repository: jrjohnsongoog/omgci}
inputs:
- name: omg-src-in
- name: omg-src-ci
run:
  path: omg-src-ci/ci/tasks/create-pull-request.sh
