---
platform: linux
image_resource:
  type: docker-image
  source: {repository: jrjohnsongoog/omgci}
inputs:
- name: omg-src-in
- name: omg-src-ci
run:
  path: omg-src-ci/ci/tasks/prepare-project.sh
params:
  google_project: replace-me
  google_json_key_data: replace-me
  env_config: replace-me
