---
platform: linux
image_resource:
  type: docker-image
  source: {repository: jrjohnsongoog/omgci}
inputs:
  - name: omg-src-in
  - name: omg-src-ci
  - name: release-version-semver
outputs:
  - name: promoted
run:
  path: omg-src-ci/ci/tasks/promote-candidate.sh
